import type { CourseGenerationInput, CourseOutline, CourseStage, TeachingActionType, TeachingSceneType, TeachingStep } from "./pipeline-types";

interface StepBlueprint {
  id: number;
  stageId: "pre-class" | "in-class" | "post-class";
  sceneType: TeachingSceneType;
  title: string;
  objective: (context: OutlineContext) => string;
  task: (context: OutlineContext) => string;
  output: string;
  rubric: string;
  theory: string;
  agent: string;
  learnerEvidence: string[];
  agentActions: TeachingActionType[];
}

interface OutlineContext {
  courseName: string;
  topic: string;
  studentProfile: string;
}

const DEFAULT_STAGES: CourseStage[] = [
  {
    id: "pre-class",
    title: "课前教学设计与准备",
    objective: "明确课程任务、学情起点、学习目标、教学资源、活动序列和评价量规。",
    stepRange: "01-08",
    stepIds: [1, 2, 3, 4, 5, 6, 7, 8],
    sceneType: "design",
  },
  {
    id: "in-class",
    title: "课中教学实施与调控",
    objective: "推进问题情境、核心概念、案例探究、协作学习、课堂对话和即时反馈。",
    stepRange: "09-16",
    stepIds: [9, 10, 11, 12, 13, 14, 15, 16],
    sceneType: "practice",
  },
  {
    id: "post-class",
    title: "课后评价反馈与持续改进",
    objective: "收集学习成果证据，诊断学习困难，形成差异化反馈、教学反思和可复用资产。",
    stepRange: "17-20",
    stepIds: [17, 18, 19, 20],
    sceneType: "evaluation",
  },
];

const STEP_BLUEPRINTS: StepBlueprint[] = [
  {
    id: 1,
    stageId: "pre-class",
    sceneType: "design",
    title: "教学情境与课程任务分析",
    objective: ({ courseName, topic }) => `厘清《${courseName}》中“${topic}”的教学情境、任务价值和材料边界。`,
    task: ({ topic, studentProfile }) => `分析 ${studentProfile} 学习“${topic}”时需要面对的真实课程任务、知识前提和应用情境。`,
    output: "课程任务说明、情境描述和资料边界清单",
    rubric: "情境与任务必须对应课程目标、学生对象和教师确认的资料边界。",
    theory: "情境学习与任务驱动教学",
    agent: "teaching-design-mentor",
    learnerEvidence: ["课程任务说明", "情境分析记录", "资料边界清单"],
    agentActions: ["generate_question", "collect_evidence"],
  },
  {
    id: 2,
    stageId: "pre-class",
    sceneType: "design",
    title: "学情分析与学习起点诊断",
    objective: ({ studentProfile, topic }) => `识别 ${studentProfile} 学习“${topic}”前的已有经验、常见误区和学习困难。`,
    task: ({ topic }) => `汇总预习数据、课堂前测或教师观察，形成“${topic}”学习起点诊断。`,
    output: "学情诊断摘要和学习起点分层",
    rubric: "诊断必须区分已有基础、概念误区、学习支持需求和可观察证据。",
    theory: "诊断性评价与最近发展区",
    agent: "evidence-rule-assistant",
    learnerEvidence: ["前测记录", "预习反馈", "教师观察记录"],
    agentActions: ["collect_evidence", "evaluate_task"],
  },
  {
    id: 3,
    stageId: "pre-class",
    sceneType: "design",
    title: "教学目标与预期学习成果设计",
    objective: ({ topic }) => `把“${topic}”转化为可观察、可评价、可迁移的学习目标。`,
    task: ({ topic }) => `生成“${topic}”的知识理解、方法应用、证据表达和反思迁移目标。`,
    output: "教学目标与预期学习成果清单",
    rubric: "目标表述必须包含行为表现、学习产出、评价证据和达成标准。",
    theory: "成果导向教育与布鲁姆认知目标分类",
    agent: "teaching-design-mentor",
    learnerEvidence: ["目标-任务对齐表", "学习成果描述", "教师确认记录"],
    agentActions: ["generate_objective", "generate_rubric"],
  },
  {
    id: 4,
    stageId: "pre-class",
    sceneType: "design",
    title: "教学内容重构与核心概念提炼",
    objective: ({ topic }) => `重构“${topic}”的知识结构，提炼学生必须掌握的核心概念和边界。`,
    task: ({ topic }) => `把教材、案例和教师材料整理为“${topic}”的概念网络、关键问题和易错点。`,
    output: "核心概念图、关键问题和易错点清单",
    rubric: "内容重构必须体现概念层级、先后关系、应用边界和学生误区。",
    theory: "概念教学与知识结构化",
    agent: "teaching-design-mentor",
    learnerEvidence: ["概念图", "关键问题清单", "易错点标注"],
    agentActions: ["generate_question", "collect_evidence"],
  },
  {
    id: 5,
    stageId: "pre-class",
    sceneType: "design",
    title: "学习资源与案例材料开发",
    objective: ({ topic }) => `开发支撑“${topic}”学习任务的课程资源、案例材料和证据片段。`,
    task: ({ topic }) => `选择或生成与“${topic}”相关的案例、资料片段、图表和课堂活动素材。`,
    output: "案例材料包和学习资源清单",
    rubric: "资源必须来源清晰、难度适配、情境真实，并能支撑后续学习证据收集。",
    theory: "案例教学与资源脚手架",
    agent: "teaching-design-mentor",
    learnerEvidence: ["案例材料", "资源索引", "资料来源说明"],
    agentActions: ["generate_case", "collect_evidence"],
  },
  {
    id: 6,
    stageId: "pre-class",
    sceneType: "design",
    title: "课前学习支架与预习任务设计",
    objective: ({ topic }) => `为“${topic}”设计课前支架，帮助学生带着问题进入课堂。`,
    task: ({ topic }) => `生成预习任务、导学问题、资料阅读路径和学生提交要求。`,
    output: "预习任务单和导学问题",
    rubric: "预习任务必须任务明确、负荷适中、能收集学习起点证据。",
    theory: "支架式教学与翻转课堂",
    agent: "teaching-design-mentor",
    learnerEvidence: ["预习任务提交", "导学问题回答", "学习困难反馈"],
    agentActions: ["generate_question", "collect_evidence"],
  },
  {
    id: 7,
    stageId: "pre-class",
    sceneType: "design",
    title: "诊断性评价与学习问题收集",
    objective: ({ topic }) => `通过诊断任务收集学生对“${topic}”的理解偏差和问题类型。`,
    task: ({ topic }) => `设计前测、快速问答或微任务，收集学生学习问题并归类。`,
    output: "诊断性评价结果和问题归类表",
    rubric: "诊断结果必须能回溯到具体学生产出、问题类型和后续教学调整。",
    theory: "学习分析与形成性评价",
    agent: "evidence-rule-assistant",
    learnerEvidence: ["前测答案", "预习问题", "学习问题归类表"],
    agentActions: ["collect_evidence", "evaluate_task"],
  },
  {
    id: 8,
    stageId: "pre-class",
    sceneType: "design",
    title: "教学过程、活动序列与评价量规设计",
    objective: ({ topic }) => `把“${topic}”的课堂过程、活动序列和评价量规统一到同一条证据链。`,
    task: () => "设计课中活动顺序、教师追问节点、学生产出要求和评价量规。",
    output: "教学流程图、活动序列和评价量规",
    rubric: "流程与量规必须对齐目标、任务、学生产出和证据来源。",
    theory: "逆向教学设计与评价量规",
    agent: "evidence-rule-assistant",
    learnerEvidence: ["活动序列", "评价量规", "证据来源对照表"],
    agentActions: ["generate_rubric", "collect_evidence"],
  },
  {
    id: 9,
    stageId: "in-class",
    sceneType: "practice",
    title: "问题情境创设与学习动机激发",
    objective: ({ topic }) => `通过问题情境激发学生进入“${topic}”学习任务。`,
    task: ({ topic }) => `呈现引入情境，提出需要学生用“${topic}”解决的课堂问题。`,
    output: "课堂导入问题和学习任务说明",
    rubric: "问题情境必须真实、开放、与课程任务直接相关，并能引出学生初始判断。",
    theory: "问题导向学习",
    agent: "teaching-design-mentor",
    learnerEvidence: ["学生初始判断", "课堂导入记录", "问题回应"],
    agentActions: ["generate_question", "simulate_student_response"],
  },
  {
    id: 10,
    stageId: "in-class",
    sceneType: "practice",
    title: "先行组织与已有经验激活",
    objective: ({ topic }) => `激活学生与“${topic}”相关的已有知识和经验。`,
    task: () => "使用先行组织、快速投票或经验分享，把学生已有理解显性化。",
    output: "先行组织图和已有经验记录",
    rubric: "经验激活必须能连接新知识、暴露误区，并服务后续概念学习。",
    theory: "先行组织者理论",
    agent: "simulated-student-agent",
    learnerEvidence: ["学生经验记录", "快速投票结果", "误区清单"],
    agentActions: ["simulate_student_response", "collect_evidence"],
  },
  {
    id: 11,
    stageId: "in-class",
    sceneType: "practice",
    title: "核心概念讲解与认知支架提供",
    objective: ({ topic }) => `围绕“${topic}”提供核心概念讲解和认知支架。`,
    task: ({ topic }) => `讲解“${topic}”的概念结构、判断边界、关键步骤和学生易错点。`,
    output: "核心概念讲解稿和认知支架",
    rubric: "讲解必须准确、层次清晰、包含例证，并回应前序诊断问题。",
    theory: "认知负荷理论与脚手架",
    agent: "teaching-design-mentor",
    learnerEvidence: ["课堂笔记", "概念检查题", "支架使用记录"],
    agentActions: ["generate_question", "evaluate_task"],
  },
  {
    id: 12,
    stageId: "in-class",
    sceneType: "practice",
    title: "案例探究与证据分析活动",
    objective: ({ topic }) => `引导学生在案例中使用证据完成“${topic}”分析。`,
    task: () => "组织学生阅读案例材料、标注证据、提出判断并说明依据。",
    output: "案例证据标注和小组分析记录",
    rubric: "证据分析必须区分事实、推论和价值判断，并说明证据适用边界。",
    theory: "案例探究与证据推理",
    agent: "simulated-student-agent",
    learnerEvidence: ["案例标注", "小组讨论记录", "证据-判断对照表"],
    agentActions: ["generate_case", "simulate_student_response", "collect_evidence"],
  },
  {
    id: 13,
    stageId: "in-class",
    sceneType: "practice",
    title: "协作学习与角色任务推进",
    objective: () => "通过角色分工和协作任务推动学生形成可展示的学习成果。",
    task: () => "分配小组角色、推进任务协作、记录讨论过程和阶段产出。",
    output: "小组任务分工、协作记录和阶段成果",
    rubric: "协作过程必须体现角色责任、共同产出、证据共享和过程记录。",
    theory: "协作学习与社会建构主义",
    agent: "simulated-student-agent",
    learnerEvidence: ["小组分工表", "协作记录", "阶段成果"],
    agentActions: ["simulate_student_response", "collect_evidence"],
  },
  {
    id: 14,
    stageId: "in-class",
    sceneType: "practice",
    title: "学习成果展示、课堂对话与追问",
    objective: () => "通过成果展示、课堂对话和教师追问深化学生理解。",
    task: () => "组织学生展示产出，教师围绕依据、边界和迁移价值进行追问。",
    output: "成果展示记录、课堂追问和学生回应",
    rubric: "展示与追问必须聚焦学习目标、证据质量和学生思维推进。",
    theory: "课堂对话与高阶提问",
    agent: "teaching-design-mentor",
    learnerEvidence: ["展示作品", "课堂追问记录", "学生回应"],
    agentActions: ["generate_question", "simulate_student_response", "collect_evidence"],
  },
  {
    id: 15,
    stageId: "in-class",
    sceneType: "practice",
    title: "形成性评价与即时反馈调节",
    objective: () => "依据课堂证据进行形成性评价，并即时调节教学节奏和支持方式。",
    task: () => "使用量规或检查表评价学生表现，生成即时反馈和调节建议。",
    output: "形成性评价记录和即时反馈",
    rubric: "反馈必须具体、可操作、对应学生证据，并说明下一步改进路径。",
    theory: "形成性评价与反馈调节",
    agent: "evidence-rule-assistant",
    learnerEvidence: ["形成性评价表", "即时反馈记录", "学生修正产出"],
    agentActions: ["evaluate_task", "generate_rubric", "collect_evidence"],
  },
  {
    id: 16,
    stageId: "in-class",
    sceneType: "practice",
    title: "课堂总结、迁移提升与课后任务衔接",
    objective: ({ topic }) => `帮助学生总结“${topic}”的学习要点，并迁移到后续课后任务。`,
    task: ({ topic }) => `组织课堂总结，形成“${topic}”迁移问题和课后延伸任务。`,
    output: "课堂总结、迁移问题和课后任务",
    rubric: "总结必须连接核心概念、课堂证据、迁移场景和课后学习要求。",
    theory: "迁移学习与反思性总结",
    agent: "teaching-design-mentor",
    learnerEvidence: ["课堂总结卡", "迁移问题回答", "课后任务说明"],
    agentActions: ["generate_question", "collect_evidence"],
  },
  {
    id: 17,
    stageId: "post-class",
    sceneType: "evaluation",
    title: "学习成果收集与表现性评价",
    objective: () => "收集学生学习成果，并基于量规完成表现性评价。",
    task: () => "汇总学生作品、课堂表现和任务提交，按评价量规形成评分记录。",
    output: "学习成果档案和表现性评价记录",
    rubric: "表现性评价必须依据明确、等级描述完整、证据链可回溯。",
    theory: "表现性评价与证据中心设计",
    agent: "evidence-rule-assistant",
    learnerEvidence: ["学生作品", "评分记录", "量规证据链"],
    agentActions: ["evaluate_task", "generate_rubric", "collect_evidence"],
  },
  {
    id: 18,
    stageId: "post-class",
    sceneType: "evaluation",
    title: "学习数据分析与学习困难诊断",
    objective: () => "分析学习数据，定位学生困难、群体差异和教学支持缺口。",
    task: () => "汇总成绩、作业、讨论和反馈数据，诊断学习困难类型。",
    output: "学习数据分析摘要和困难诊断",
    rubric: "诊断必须基于数据证据，区分个体、群体和教学设计层面问题。",
    theory: "学习分析与教育数据诊断",
    agent: "evidence-rule-assistant",
    learnerEvidence: ["学习数据摘要", "困难诊断表", "证据引用"],
    agentActions: ["collect_evidence", "evaluate_task"],
  },
  {
    id: 19,
    stageId: "post-class",
    sceneType: "evaluation",
    title: "差异化反馈、补救教学与拓展支持",
    objective: () => "根据学习困难和表现差异生成反馈、补救教学和拓展支持方案。",
    task: () => "为不同学生群体生成可执行反馈、补救任务和拓展学习建议。",
    output: "差异化反馈方案、补救任务和拓展支持清单",
    rubric: "反馈与支持必须指向具体证据、具体学生需求和可执行改进行动。",
    theory: "差异化教学与可操作反馈",
    agent: "teaching-design-mentor",
    learnerEvidence: ["反馈记录", "补救任务", "拓展学习建议"],
    agentActions: ["generate_question", "evaluate_task", "collect_evidence"],
  },
  {
    id: 20,
    stageId: "post-class",
    sceneType: "reflection",
    title: "教学反思、资源沉淀与持续改进",
    objective: () => "基于证据完成教学反思，沉淀可复用资源并规划下一轮改进。",
    task: () => "整理教学证据、评价结果、教师反思和资产入库建议。",
    output: "教学反思报告、资源沉淀清单和持续改进计划",
    rubric: "反思必须区分证据、判断和改进行动，并说明资产复用边界。",
    theory: "反思性实践与持续改进",
    agent: "course-asset-curator",
    learnerEvidence: ["教学反思", "资产入库记录", "改进行动计划"],
    agentActions: ["collect_evidence", "evaluate_task", "export_asset"],
  },
];

export function generateCourseOutline(input: CourseGenerationInput): CourseOutline {
  const context: OutlineContext = {
    topic: input.topic || "SWOT 分析",
    courseName: input.courseName || "管理学原理",
    studentProfile: input.studentProfile || "药事管理本科生",
  };
  const steps = STEP_BLUEPRINTS.map((step) => materializeStep(step, context));
  return {
    id: stableId("outline", input.courseId, context.topic),
    title: `${context.courseName} · ${context.topic} 课程教学运行骨架`,
    courseName: context.courseName,
    topic: context.topic,
    studentProfile: context.studentProfile,
    stages: DEFAULT_STAGES,
    steps,
    objectives: [
      `解释 ${context.topic} 的关键概念、判断边界和课程价值。`,
      `面向 ${context.studentProfile} 设计可执行、可评价、可反思的教学实践任务。`,
      "形成由学习目标、课堂活动、评价证据和导出资产贯通的教学闭环。",
    ],
    constraints: input.constraints.length
      ? input.constraints
      : ["2 学时", "新教师可审校", "所有评价维度必须绑定 evidenceRefs"],
    sourceBoundary: input.sourceBoundary || "仅使用教师确认的课程资料、课堂记录和授权学习数据。",
  };
}

function materializeStep(step: StepBlueprint, context: OutlineContext): TeachingStep {
  return {
    id: step.id,
    stageId: step.stageId,
    sceneType: step.sceneType,
    title: step.title,
    objective: step.objective(context),
    task: step.task(context),
    output: step.output,
    rubric: step.rubric,
    theory: step.theory,
    agent: step.agent,
    learnerEvidence: step.learnerEvidence,
    agentActions: step.agentActions,
  };
}

function stableId(prefix: string, courseId: string, topic: string): string {
  return `${prefix}-${courseId || "course"}-${topic}`.toLowerCase().replace(/[^a-z0-9\u4e00-\u9fa5]+/gi, "-");
}
